### ISSUE TITLE
MockException : IDisposable.Dispose() invocation failed with mock behavior Strict.

### ISSUE THREAD

**Issue by ptr1120** [autofac/Autofac.Extras.Moq#19] opened 2018-08-05 10:04 UTC
Hello,

thanks for this great library I used it with success in several projects.
In a new project, I am experiencing a strange behavior when mocking interfaces that inherit from `IDisposable`.
With the following code:

``` 
public interface IInterface:IDisposable
{ }
public class MyClass
 {
     private readonly IInterface _interface;

        public MyClass(IInterface @interface)
        {
            _interface = @interface;
        }
 }
 [Test]
 public void Method_Scenario_Expectation()
 {
            using (_autoMock = AutoMock.GetStrict())
            {
                var sut = _autoMock.Create<MyClass>();
            }
 }
 ```
I get a test failure:
```Moq.MockException : IDisposable.Dispose() invocation failed with mock behavior Strict.
All invocations on the mock must have a corresponding setup.
   at Moq.FindAndExecuteMatchingSetup.Handle(Invocation invocation, Mock mock) in C:\projects\moq4\Source\Interception\InterceptionAspects.cs:line 172
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation) in C:\projects\moq4\Source\Interception\Mock.cs:line 58
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Autofac.Core.Disposer.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Container.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Extras.Moq.AutoMock.Dispose(Boolean disposing)
   at Autofac.Extras.Moq.AutoMock.Dispose()
```

So during the disposal of the container (after `Verify()`) the dependency gets disposed, which leads to that failure. When I setup the `Dispose()` method than `Verify()` fails, because it hasn't been called.
Any idea how to overcome this? I am using Autofac version 4.8.1, Moq version 4.9.0.

Best regards,
Peter

**Comment by tillig** [comment] 2018-10-23 18:15
I added [a unit test to see if I could reproduce the issue](https://github.com/autofac/Autofac.Extras.Moq/blob/33a8cb3da49c2e7470791f4d996250ac8c681a91/test/Autofac.Extras.Moq.Test/AutoMockFixture.cs#L65) but I can't. That said, the base Autofac.Extras.Moq library uses Moq 4.7.0 so things may have changed in 4.9.0.

Since I can't repro it, I'm going to close the issue. Here's what I'd recommend:

Clone the `develop` branch of this repo and try updating versions of Autofac and Moq to see if you can repro the issue here. If you can, post back here with the magic combo of versions that causes the failure. If you can't repro the issue in here, it means there's something else going on with your code/setup that is outside our abilities to troubleshoot.

**Closed by tillig** 2018-10-23 18:15 UTC

**Comment by JarkoDubbeldam** [comment] 2020-05-26 09:20
I am having a similar issue with Moq 4.13.1, Autofac.Extras.Moq 5.0.0.

```
    [Test]
    public void DisposableMockTest() {
      using var mock = AutoMock.GetStrict();
      var instance = mock.Create<ClassWithDisposableDependancy>();

      var result = instance.DoStuff();
      Assert.That(result, Is.EqualTo(5));
    }

    public class ClassWithDisposableDependancy {
      private readonly IDisposable disposable;

      public ClassWithDisposableDependancy(IDisposable disposable) {
        this.disposable = disposable;
      }

      public int DoStuff() {
        return 5;
      }
    }
```
Where it fails with the following exception:

```
Message: 
    System.AggregateException : One or more errors occurred. (Rethrown)
      ----> NUnit.Framework.Internal.NUnitException : Rethrown
      ----> Moq.MockException : IDisposable.Dispose() invocation failed with mock behavior Strict.
    All invocations on the mock must have a corresponding setup.
  Stack Trace: 
    Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    Task.Wait(Int32 millisecondsTimeout)
    TimeoutCommand.Execute(TestExecutionContext context)
    --NUnitException
    Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args)
    MethodWrapper.Invoke(Object fixture, Object[] args)
    TestMethodCommand.InvokeTestMethod(TestExecutionContext context)
    TestMethodCommand.RunTestMethod(TestExecutionContext context)
    TestMethodCommand.Execute(TestExecutionContext context)
    <>c__DisplayClass2_0.<Execute>b__0()
    Task`1.InnerInvoke()
    <.cctor>b__274_0(Object obj)
    ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location where exception was thrown ---
    ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
    --MockException
    FailForStrictMock.Handle(Invocation invocation, Mock mock)
    IInterceptor.Intercept(Invocation invocation)
    Interceptor.Intercept(IInvocation invocation)
    AbstractInvocation.Proceed()
    IDisposableProxy.Dispose()
    Disposer.Dispose(Boolean disposing)
    Disposable.Dispose()
    LifetimeScope.Dispose(Boolean disposing)
    Disposable.Dispose()
    Container.Dispose(Boolean disposing)
    Disposable.Dispose()
    AutoMock.Dispose(Boolean disposing)
    AutoMock.Dispose()
    Example.DisposableMockTest() line 177
```

It seems that when the Automock container is disposed, it's disposing all of its registered types. The mocked types being strict, this fails and throws. I'm not sure if it is possible to make a special case for mocked items, since it looks like it might be in the common Autofac code, which might be problematic.
